# CMake generated Testfile for 
# Source directory: /Users/pavel/libcbor/test
# Build directory: /Users/pavel/libcbor/cmake-build/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(array_encoders_test "/Users/pavel/libcbor/cmake-build/test/array_encoders_test")
set_tests_properties(array_encoders_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(array_test "/Users/pavel/libcbor/cmake-build/test/array_test")
set_tests_properties(array_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(bad_inputs_test "/Users/pavel/libcbor/cmake-build/test/bad_inputs_test")
set_tests_properties(bad_inputs_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(bytestring_encoders_test "/Users/pavel/libcbor/cmake-build/test/bytestring_encoders_test")
set_tests_properties(bytestring_encoders_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(bytestring_test "/Users/pavel/libcbor/cmake-build/test/bytestring_test")
set_tests_properties(bytestring_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(callbacks_test "/Users/pavel/libcbor/cmake-build/test/callbacks_test")
set_tests_properties(callbacks_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(cbor_serialize_test "/Users/pavel/libcbor/cmake-build/test/cbor_serialize_test")
set_tests_properties(cbor_serialize_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(cbor_stream_decode_test "/Users/pavel/libcbor/cmake-build/test/cbor_stream_decode_test")
set_tests_properties(cbor_stream_decode_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(copy_test "/Users/pavel/libcbor/cmake-build/test/copy_test")
set_tests_properties(copy_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(float_ctrl_encoders_test "/Users/pavel/libcbor/cmake-build/test/float_ctrl_encoders_test")
set_tests_properties(float_ctrl_encoders_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(float_ctrl_test "/Users/pavel/libcbor/cmake-build/test/float_ctrl_test")
set_tests_properties(float_ctrl_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(fuzz_test "/Users/pavel/libcbor/cmake-build/test/fuzz_test")
set_tests_properties(fuzz_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(map_encoders_test "/Users/pavel/libcbor/cmake-build/test/map_encoders_test")
set_tests_properties(map_encoders_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(map_test "/Users/pavel/libcbor/cmake-build/test/map_test")
set_tests_properties(map_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(memory_utils_test "/Users/pavel/libcbor/cmake-build/test/memory_utils_test")
set_tests_properties(memory_utils_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(negint_encoders_test "/Users/pavel/libcbor/cmake-build/test/negint_encoders_test")
set_tests_properties(negint_encoders_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(negint_test "/Users/pavel/libcbor/cmake-build/test/negint_test")
set_tests_properties(negint_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(pretty_printer_test "/Users/pavel/libcbor/cmake-build/test/pretty_printer_test")
set_tests_properties(pretty_printer_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(stack_over_limit_test "/Users/pavel/libcbor/cmake-build/test/stack_over_limit_test")
set_tests_properties(stack_over_limit_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(string_encoders_test "/Users/pavel/libcbor/cmake-build/test/string_encoders_test")
set_tests_properties(string_encoders_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(string_test "/Users/pavel/libcbor/cmake-build/test/string_test")
set_tests_properties(string_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(tag_encoders_test "/Users/pavel/libcbor/cmake-build/test/tag_encoders_test")
set_tests_properties(tag_encoders_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(tag_test "/Users/pavel/libcbor/cmake-build/test/tag_test")
set_tests_properties(tag_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(uint_encoders_test "/Users/pavel/libcbor/cmake-build/test/uint_encoders_test")
set_tests_properties(uint_encoders_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(uint_test "/Users/pavel/libcbor/cmake-build/test/uint_test")
set_tests_properties(uint_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
add_test(unicode_test "/Users/pavel/libcbor/cmake-build/test/unicode_test")
set_tests_properties(unicode_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/pavel/libcbor/test/CMakeLists.txt;22;add_test;/Users/pavel/libcbor/test/CMakeLists.txt;0;")
